export const SET_CAL_TIME_PERIOD = "SET_CAL_TIME_PERIOD";
export const SET_CAL_START_DATE = "SET_CAL_START_DATE";
export const SET_CAL_CURRENT_DATE = "SET_CAL_CURRENT_DATE";
export const SET_CAL_SLIDE_COUNT = "SET_CAL_SLIDE_COUNT";
