export const MAP_CENTER_COORDS = "MAP_CENTER_COORDS";
export const MAP_INSTANCE = "MAP_INSTANCE";
export const MAP_REF = "MAP_REF";
export const MAP_ZOOM = "MAP_ZOOM";

export const MAP_ZOOM_ACTIVE = "MAP_ZOOM_ACTIVE";
export const MAP_MOVE_ACTIVE = "MAP_MOVE_ACTIVE";

export const MAP_EASE_TO = "MAP_EASE_TO";
export const MAP_FLY_TO = "MAP_FLY_TO";

export const MAP_CENTER_ON_CLIENT = "MAP_CENTER_ON_CLIENT";
export const MAP_CENTER_ON_ADDRESS = "MAP_CENTER_ON_ADDRESS";
export const MAP_CENTER_ON_COORDS = "MAP_CENTER_ON_COORDS";
export const MAP_ANIMATION_OPTIONS = "MAP_ANIMATION_OPTIONS";
export const MAP_PADDING = "MAP_PADDING";
