export const calendarConstants = {
  CAL_MODE: "CAL_MODE",
  CAL_TIME_PERIOD: "CAL_TIME_PERIOD",
  CAL_START_DATE: "CAL_START_DATE",
  CAL_CURRENT_DATE: "CAL_CURRENT_DATE",
  HOVERED_SEGMENT: "HOVERED_SEGMENT",
};
