export const getCalMode = state => state.calendarReducer.calMode;
export const getInViewEventsData = state => state.calendarReducer.inViewEventsData;
export const getCalTimePeriod = state => state.calendarReducer.calTimePeriod;
export const getCalCurrentDate = state => state.calendarReducer.calCurrentDate;
export const getCalStartDate = state => state.calendarReducer.calStartDate;
export const getSliderXDistance = state => state.calendarReducer.sliderXDistance;
export const getSlideCount = state => state.calendarReducer.slideCount;
export const getSlideWidth = state => state.calendarReducer.slideWidth;
export const getTimeTable = state => state.calendarReducer.timeTable;