export const CAL_MODE = "CAL_MODE";
export const TOGGLE_CAL_OPEN = "TOGGLE_CAL_OPEN";
export const TOGGLE_CAL_CLOSED = "TOGGLE_CAL_CLOSED";
export const CAL_TIME_PERIOD = "CAL_TIME_PERIOD";
export const CAL_START_DATE = "CAL_START_DATE";
export const CAL_CURRENT_DATE = "CAL_CURRENT_DATE";
export const CAL_TIMETABLE = "CAL_TIMETABLE";
export const SLIDE_COUNT = "SLIDE_COUNT";
export const SLIDE_WIDTH = "SLIDE_WIDTH";
export const SLIDER_X_DISTANCE = "SLIDER_X_DISTANCE";
export const QUERY_IN_VIEW_EVENTS_DATA = "QUERY_IN_VIEW_EVENTS_DATA";
export const IN_VIEW_EVENTS_DATA = "IN_VIEW_EVENTS_DATA";
export const TIMETABLE_INTERVALS = "TIMETABLE_INTERVALS";

