export const EVENT_MODAL_MODE = "EVENT_MODAL_MODE";
export const SET_EVENT_MODAL = "SET_EVENT_MODAL";
export const SET_EVENT = "SET_EVENT";
export const CREATE_EVENT = "CREATE_EVENT";
export const UPDATE_EVENT = "UPDATE_EVENT";
export const START_NEW_EVENT = "START_NEW_EVENT";
export const OPEN_EVENT_FROM_MARKER = "OPEN_EVENT_FROM_MARKER";

export const EVENT_MODAL_ANIM_START = "EVENT_MODAL_ANIM_START";
export const EVENT_MODAL_ANIM_END = "EVENT_MODAL_ANIM_END";

